FROM --platform=$BUILDPLATFORM mcr.microsoft.com/devcontainers/python:1-3.12-bookworm

ENV DEBIAN_FRONTEND=noninteractive
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /workspace

RUN apt-get update \
    && apt-get -y install --no-install-recommends libxml2-dev libxslt1-dev zlib1g-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN pip install --upgrade pip && pipx install uv && chown -R vscode:vscode /workspace

USER vscode

COPY pyproject.toml uv.lock ./
RUN uv venv && uv sync --all-extras --dev

COPY . .

WORKDIR /workspace/app
